#!/bin/bash

### VARIABLES ###

font="SourceCodeVF:style=Semibold:pixelsize=13:antialias=true"
nb="black"
sb="#646464"
lines=5
border_width=2
line_height=19
prompt="Exit"
DMENU="dmenu -r -i -x 590 -y 300 -z 200 -fn $font -nb $nb -sb $sb -l $lines -bw $border_width -h $line_height" 


### MAIN-FUNCTION ###

main() {
    choice=`echo -e "Shutdown\nRestart\nLogout\nSuspend\nLock" | $DMENU`
    if [ ${#choice} == 0 ]; then
        exit
    fi
    case $choice in 
        Shutdown)
            systemctl poweroff;;
        Restart)
            systemctl reboot;;
        Logout)
            loginctl terminate-user $USER;;
        Suspend)
            systemctl suspend;;
        Lock)
            sleep 0.15
            lock;;
    esac
}

### MAIN ###

main

### END ###
