#!/bin/bash

### VARIABLES ###

font="SourceCodeVF:style=Semibold:pixelsize=13:antialias=true"
nb="black"
sb="#646464"
lines=20
border_width=2
line_height=0
prompt="Files"
command_="ls -A"
DMENU="dmenu -cn -r -x 480 -y 200 -z 400 -i -fn $font -nb $nb -sb $sb -l $lines -bw $border_width -p $prompt"

### MAIN-FUNCTION ###

main() {
    while :
    do
	    input=`ls -A | $DMENU`
	    len_of_input=${#input}
	    if [ "$len_of_input" == 0 ]; then exit 0; fi
		if [ "`file $input -b | awk '{ print $1 }'`" == symbolic ]; then path=`file $input -b | awk '{ print $4 }'`;
        else path=`pwd`/$input; fi
		if [ -d "$path" ]; then cd $input;
		elif [ -f "$path" ]; then xdg-open "$path";
	    else break; fi
    done
}

### MAIN ###

main

### END ###
