#!/bin/bash

### VARIABLES ###

font="SourceCodeVF:style=Semibold:pixelsize=13:antialias=true"
nb="black"
sb="#646464"
lines=20
border_width=2
line_height=0
prompt="Files"
command_="ls -A"
DMENU="dmenu -r -cn -x 480 -y 200 -z 400 -i -fn $font -nb $nb -sb $sb -l $lines -bw $border_width -p $prompt"

### MAIN-FUNCTION ###

main() {
   while :
    do
        contents=()
        if [ $PWD != '/' ]; then contents+=("<--"); fi
        while IFS= read -r line;
        do
            contents+=("$line")
        done < <(ls -A)
        input=`printf "%s\n" "${contents[@]}" | $DMENU`
        len_of_input=${#input}
        if [ "$len_of_input" == 0 ]; then exit 0; fi
        if [ "$input" == '<--' ]; then cd ..; continue; fi
        if [ -L "$input" ]; then
            path=$(readlink -f "$input")
        else
            path=$(realpath "$input")
        fi
        if [ -d "$path" ]; then
            cd "$input"
        elif [ -f "$path" ]; then
            mimetype=$(file -b --mime-type "$path")
            case "$mimetype" in
                "text/"*)
                    st -e vim "$path";;
                "application/pdf")
                    zathura "$path";;
                "image/"*)
                    feh "$path" ;;
                "video/"*)
                    vlc "$path";;
                "audio/"*)
                    audacious "$path"
                    ;;
                *)
                    echo "No application set for opening $input"
                    ;;
            esac
        else
            break
        fi
    done
}

### MAIN ###

main

### END ###

