#!/bin/bash

### VARIABLES ###

font="SourceCodeVF:style=Semibold:pixelsize=12:antialias=true"
nb="black"
sb="#646464"
lines=10
border_width=2
line_height=20
prompt="Filebrowser"
DMENU="dmenu -i -fn $font -nb $nb -sb $sb -l $lines -bw $border_width -h $line_height -p $prompt"

### MAIN-FUNSTION ###

main() {
    while :
    do
	    input=`ls -A | $DMENU`
	    len_of_input=${#input}
	    if [ "$len_of_input" == 0 ]; then exit 0; fi
		if [ "`file $input -b | awk '{ print $1 }'`" == symbolic ]; then path=`file $input -b | awk '{ print $4 }'`;
        else path=`pwd`/$input; fi
		if [ -d "$path" ]; then cd $input;
		elif [ -f "$path" ]; then xdg-open "$path";
	    else break; fi
    done
}

### MAIN ###

main

### END ###
