#!/bin/bash

### VARIABLES ###

font="SourceCodeVF:style=Semibold:pixelsize=13:antialias=true"
font_1="SourceCodeVF:style=Semibold:pixelsize=11.5:antialias=true"
nb="black"
sb="#646464"
lines=20
border_width=2
line_height=19
prompt="Kill?"
DMENU="dmenu -cn -r -i -x 500 -y 200 -z 400 -fn $font -nb $nb -sb $sb -l $lines -bw $border_width -p $prompt"
DMENU_1="dmenu -r -i -fn $font_1 -nb $nb -sb $sb -p 'kill?-(Yes/No)' -h $line_height"

### MAIN-FUNCTION ###

main() { 
    selected_with_pid=`ps -a -u $USER | $DMENU` 
    if [ ! -z "$selected_with_pid" ]; then
        selected=`echo $selected_with_pid | awk '{print $2}'`
        answer=`echo -e "Yes\nNo" | $DMENU_1`
        if [ "$answer" == "Yes" ]; then
            selpid="$(awk '{print $1}' <<< $selected_with_pid)";
            kill -9 $selpid
        fi
    fi
    exit 0
}

### MAIN ###

main

### END ###
