#!/bin/bash

### VARIABLES ###

font="SourceCodeVF:style=Semibold:pixelsize=11.5:antialias=true"
nb="black"
sb="#646464"
lines=0
border_width=0
line_height=19
prompt="Executables"
DMENU="dmenu -cn -r -i -fn $font -nb $nb -sb $sb -l  $lines -bw $border_width -p $prompt -h $line_height "

### MAIN-FUNCTION ###

main() {
    $(dmenu_path | $DMENU)
}

### MAIN ###

main

### END ###
