#!/bin/bash

### VARIABLES ###

font="SourceCodeVF:style=Semibold:pixelsize=11.5:antialias=true"
nb="black"
sb="#646464"
lines=0
border_width=0
line_height=19
prompt="Workspaces-nav"
DMENU="dmenu -r -i -fn $font -nb $nb -sb $sb -l $lines -bw $border_width -p $prompt -h $line_height "

### MAIN-FUNCTION ###

main() {
    dm=`wmctrl -d | awk '{print $9}' | $DMENU`
    if [ "${#dm}" != 0 ]; then
	    wrkspnum=`wmctrl -d | grep "$dm" | awk '{print $1}'`
	    wmctrl -s $wrkspnum
    fi
}

### MAIN ###

main          

### END ###
